### ISSUE TITLE
Min/Max bar placement

### ISSUE THREAD

**Issue by dotlineX** [datguypiko/Firefox-Mod#4]
Hi, loved your project but there is an issue when I commented `#TabsToolbar > .titlebar-buttonbox-container{ visibility: collapse !important; }` it looks like the following,

![Annotation 2020-04-12 114929](https://user-images.githubusercontent.com/59593757/79064725-fc6c8680-7c9a-11ea-8e5f-3ffbb723431f.png)

Why is this happening?

**Comment by Neikon** [comment]
because those buttons are in the title bar (tab bar), and this theme just changes the order of the bars in Firefox.
on the other hand this default theme is intended to be used with the addon that adds the mac style close buttons.

I use firefox's default bar order  and tabs and that buttons are on top. I like it better this way.

**Comment by dotlineX** [comment]
Oh okay thats why you mentioned that extension in the readme file. Thanks
